title: Understanding and using Array and array methods
author: Stanley Hayford
email: hayfordstanley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This guide will help you understand functions, higher order functions, lambda functions and how to use all the array methods so you can use them effectively

# social links
twitter_username: stanley_hayford # DO NOT include the @ character, or else the build will fail!
github_username:  stanleyHayes # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
